name: Keep Supabase alive

on:
  schedule:
    - cron: "0 9 * * 1,4" # Lunes y jueves a las 9:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl https://backend-proyecto-arnau-edgar-production.up.railway.app/
